Development
KelwayHao/PacManAnimationView pull request #1
Opened 2022-04-15 22:03 UTC by KelwayHao

2022-04-16 10:03 UTC, Vlad94051 requested changes

2022-04-16 10:03 UTC, Vlad94051 commented on app/src/main/java/com/example/pacmananimationview/PacManView.kt
> +                colorPacMan =
слово color в конце, так у всех параметров принято

2022-04-16 10:03 UTC, Vlad94051 commented on app/src/main/java/com/example/pacmananimationview/PacManView.kt
> +                repeatCount = ValueAnimator.INFINITE
а зачем эти параметры? (ответь в лс)

2022-04-16 10:03 UTC, Vlad94051 commented on app/src/main/java/com/example/pacmananimationview/PacManView.kt
> +    override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
зачем переопределять onMeasure и ничего в нем не писать?

2022-04-16 10:03 UTC, Vlad94051 commented on app/src/main/java/com/example/pacmananimationview/PacManView.kt
> +    }
зачем это в экстеншн выносить?

2022-04-17 09:31 UTC, KelwayHao commented on app/src/main/java/com/example/pacmananimationview/MainActivity.kt
> +        binding = ActivityMainBinding.inflate(layoutInflater)
done

2022-04-17 09:39 UTC, KelwayHao commented on app/src/main/java/com/example/pacmananimationview/PacManView.kt
> +                colorPacMan =
done

2022-04-17 12:52 UTC, Vinny94051 approved these changes

2022-04-18 08:28 UTC, merged